#page title
page_title                                : Are You Ready To Be An Elite                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : org.pursuit.elite                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : Desktop/EliteBetaLogo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Elite                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A sports application which tracks your casual competitive games using Elo-Ranking and your location

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ibraheem K. Rawlinson (Creator)                                
your_link                                 : https://github.com/Ibraheemraw                     
your_city                                 : New York                                 
email_address                             : ibraheemrawlinson@pursuit.org

your_name                                 : Manny (Creator)                                
your_link                                 : https://github.com/manolovayusuf                     
your_city                                 : New York                                 
email_address                             : manolovayusuf@pursuit.org

your_name                                 : Pritesh Nadiadhara (Creator)                                
your_link                                 : https://github.com/PNadiadhara                    
your_city                                 : New York                                 
email_address                             : priteshnadiadhara@pursuit.org

your_name                                 : Leandro Wauters (Creator)                                
your_link                                 : https://github.com/leandrowauters                   
your_city                                 : New York                                 
email_address                             : leandrowauters@pursuit.org

facebook_username                         :                                           
instagram_username                        : IAmAnElite
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Creating Games
    description                           : Using bluetooth users are able to set up 1 vs 1 games on the app in the park they are currently in
    fontawesome_icon_name                 : magic
    
  - title                                 : Park filtering 
    description                           : Finds the nearest parks within your area and you are able to choose to see basketball courts or handball courts near you.
    fontawesome_icon_name                 : mobile

  - title                                 : Post To Social Meida (Next Version)
    description                           : User is able to post a snapshot of the game they have logged in to one of their social media channels
    fontawesome_icon_name                 : sync
  
  - title                                 : User Stats (Next Version)
    description                           : Users are able to view their the games they have one theough their profile 
    fontawesome_icon_name                 : star

  - title                                 : Facebook Login (Next Verison)
    description                           : Users will be able to login with their facebook Account
    fontawesome_icon_name                 : link


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




remote_theme: emilbaehr/automatic-app-landing-page
